### ISSUE TITLE
Is it Windows compatible?

### ISSUE THREAD

**Issue by wargebitebane-glich** [sleepinggenius2/gosmi#10]
Getting "panic: Body: Identity: Oid: SubIdentifiers: can not parse into empty struct parser.SubIdentifier" when running example from cmd/parse.

**Comment by sleepinggenius2** [comment]
That error is due to changes that were made in the participle library and should be fixed with 80a996c. I would suggest using Go modules to prevent dependency issues like that.

I have not personally tested the library on Windows, but I wrote the code so that it should be supported. Please let me know if you run into any more problems.

**Comment by wargebitebane-glich** [comment]
Yes it helped. thanks
